apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: mysql
  labels:
    app: mysql
spec:
  dnsPolicy: Default
  containers:
    - name: mysql-client
      image: mysql:5.7.14
      command: ["/bin/sh"]
      args:
        - "-c"
        - "while true; do sleep 3600; done"
